/* The following code was generated by JFlex 1.7.0 */

/* 1. Package e importaciones */
package Language;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import Painter.WordPainter;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/Language/ScannerF.jflex</tt>
 */
public class ScannerF implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  4,  6,  6,  5,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1, 41,  2,  0,  0, 40, 44, 10, 46, 47, 13, 36, 50, 37, 11, 12, 
     9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 51, 52, 42, 38, 43, 53, 
     0,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 
     8,  8,  8, 21,  8,  8,  8,  8,  8,  8,  8,  0,  3,  0, 39,  7, 
     0, 15, 25, 28, 20, 27, 31, 24, 29, 16,  8, 34, 26, 14, 17, 19, 
    35,  8, 23, 32, 22, 30, 18, 33,  8,  8,  8, 48, 45, 49,  0,  0, 
     0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\2\1\1\1\3\1\4"+
    "\1\1\1\5\1\6\16\3\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\2\1\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\0\1\27\5\0"+
    "\1\30\1\0\2\3\1\31\1\3\1\32\17\3\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\0\1\3\1\47\15\3\1\50"+
    "\3\3\1\30\1\51\1\52\3\3\1\53\3\3\1\54"+
    "\1\55\1\3\1\56\11\3\1\57\1\3\1\60\1\3"+
    "\1\61\1\62\1\63\1\3\1\64\1\65\2\3\1\66"+
    "\1\67\1\70\1\3\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\66\0\330\0\u010e\0\u0144"+
    "\0\u017a\0\u01b0\0\66\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be"+
    "\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e"+
    "\0\u04a4\0\u04da\0\u0510\0\u0546\0\66\0\66\0\u057c\0\u05b2"+
    "\0\u05e8\0\u061e\0\u0654\0\66\0\66\0\66\0\66\0\66"+
    "\0\66\0\66\0\66\0\242\0\66\0\u068a\0\330\0\u06c0"+
    "\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce\0\u0804\0\u010e\0\u083a"+
    "\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea"+
    "\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a"+
    "\0\66\0\66\0\66\0\66\0\66\0\66\0\66\0\66"+
    "\0\66\0\66\0\u06c0\0\66\0\u0bd0\0\u0c06\0\u010e\0\u0c3c"+
    "\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec"+
    "\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u010e\0\u0efa\0\u0f30\0\u0f66"+
    "\0\66\0\u010e\0\u010e\0\u0f9c\0\u0fd2\0\u1008\0\u010e\0\u103e"+
    "\0\u1074\0\u10aa\0\u010e\0\u010e\0\u10e0\0\u010e\0\u1116\0\u114c"+
    "\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u010e"+
    "\0\u12fc\0\u010e\0\u1332\0\u010e\0\u010e\0\u010e\0\u1368\0\u010e"+
    "\0\u010e\0\u139e\0\u13d4\0\u010e\0\u010e\0\u010e\0\u140a\0\u010e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\3\1\0\1\6"+
    "\1\7\1\10\1\11\1\2\1\12\1\13\1\14\1\7"+
    "\1\15\1\7\1\16\1\7\1\17\1\20\1\21\1\22"+
    "\1\7\1\23\1\7\1\24\1\25\2\7\1\26\1\27"+
    "\1\30\1\7\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\67\0\1\3\3\0"+
    "\1\3\60\0\2\54\1\55\1\56\1\0\61\54\7\0"+
    "\1\57\1\7\5\0\26\7\31\0\3\7\4\0\26\7"+
    "\33\0\1\10\1\0\1\60\52\0\2\61\1\0\1\62"+
    "\1\0\61\61\14\0\1\63\1\64\57\0\3\7\4\0"+
    "\1\7\1\65\24\7\31\0\3\7\4\0\3\7\1\66"+
    "\15\7\1\67\4\7\31\0\3\7\4\0\5\7\1\70"+
    "\20\7\31\0\3\7\4\0\5\7\1\71\7\7\1\72"+
    "\10\7\31\0\3\7\4\0\10\7\1\73\15\7\31\0"+
    "\3\7\4\0\11\7\1\74\14\7\31\0\3\7\4\0"+
    "\15\7\1\75\10\7\31\0\3\7\4\0\5\7\1\76"+
    "\3\7\1\77\14\7\31\0\3\7\4\0\14\7\1\100"+
    "\11\7\31\0\3\7\4\0\1\7\1\101\3\7\1\102"+
    "\11\7\1\103\6\7\31\0\3\7\4\0\1\7\1\104"+
    "\3\7\1\105\20\7\31\0\3\7\4\0\23\7\1\106"+
    "\2\7\31\0\3\7\4\0\17\7\1\107\6\7\31\0"+
    "\3\7\4\0\11\7\1\110\14\7\66\0\1\111\1\0"+
    "\1\112\64\0\1\113\1\114\65\0\1\115\65\0\1\116"+
    "\65\0\1\117\65\0\1\120\73\0\1\121\66\0\1\122"+
    "\10\0\4\54\3\0\57\54\11\0\1\123\66\0\1\124"+
    "\53\0\4\61\3\0\57\61\4\63\2\0\60\63\15\64"+
    "\1\125\50\64\7\0\3\7\4\0\2\7\1\126\23\7"+
    "\31\0\3\7\4\0\10\7\1\127\15\7\31\0\3\7"+
    "\4\0\2\7\1\130\23\7\31\0\3\7\4\0\20\7"+
    "\1\131\5\7\31\0\3\7\4\0\21\7\1\132\4\7"+
    "\31\0\3\7\4\0\11\7\1\133\14\7\31\0\3\7"+
    "\4\0\20\7\1\134\5\7\31\0\3\7\4\0\10\7"+
    "\1\135\15\7\31\0\3\7\4\0\5\7\1\136\20\7"+
    "\31\0\3\7\4\0\15\7\1\137\10\7\31\0\3\7"+
    "\4\0\22\7\1\140\3\7\31\0\3\7\4\0\22\7"+
    "\1\141\3\7\31\0\3\7\4\0\3\7\1\142\22\7"+
    "\31\0\3\7\4\0\1\7\1\143\24\7\31\0\3\7"+
    "\4\0\14\7\1\144\11\7\31\0\3\7\4\0\11\7"+
    "\1\145\14\7\31\0\3\7\4\0\2\7\1\146\23\7"+
    "\31\0\3\7\4\0\2\7\1\147\23\7\31\0\3\7"+
    "\4\0\2\7\1\150\23\7\22\0\14\64\1\151\1\125"+
    "\50\64\7\0\3\7\4\0\3\7\1\152\22\7\31\0"+
    "\3\7\4\0\6\7\1\153\17\7\31\0\3\7\4\0"+
    "\13\7\1\154\12\7\31\0\3\7\4\0\1\7\1\155"+
    "\24\7\31\0\3\7\4\0\2\7\1\156\23\7\31\0"+
    "\3\7\4\0\15\7\1\157\10\7\31\0\3\7\4\0"+
    "\20\7\1\160\5\7\31\0\3\7\4\0\14\7\1\161"+
    "\11\7\31\0\3\7\4\0\1\7\1\162\24\7\31\0"+
    "\3\7\4\0\15\7\1\163\10\7\31\0\3\7\4\0"+
    "\15\7\1\164\10\7\31\0\3\7\4\0\10\7\1\165"+
    "\15\7\31\0\3\7\4\0\11\7\1\166\14\7\31\0"+
    "\3\7\4\0\22\7\1\167\3\7\31\0\3\7\4\0"+
    "\10\7\1\170\15\7\31\0\3\7\4\0\14\7\1\171"+
    "\11\7\31\0\3\7\4\0\3\7\1\172\22\7\31\0"+
    "\3\7\4\0\14\7\1\173\11\7\31\0\3\7\4\0"+
    "\20\7\1\174\5\7\31\0\3\7\4\0\3\7\1\175"+
    "\22\7\31\0\3\7\4\0\11\7\1\176\14\7\31\0"+
    "\3\7\4\0\15\7\1\177\10\7\31\0\3\7\4\0"+
    "\24\7\1\200\1\7\31\0\3\7\4\0\2\7\1\201"+
    "\23\7\31\0\3\7\4\0\15\7\1\202\10\7\31\0"+
    "\3\7\4\0\16\7\1\203\7\7\31\0\3\7\4\0"+
    "\15\7\1\204\10\7\31\0\3\7\4\0\10\7\1\205"+
    "\15\7\31\0\3\7\4\0\15\7\1\206\10\7\31\0"+
    "\3\7\4\0\14\7\1\207\11\7\31\0\3\7\4\0"+
    "\12\7\1\210\13\7\31\0\3\7\4\0\3\7\1\211"+
    "\22\7\31\0\3\7\4\0\1\7\1\212\24\7\31\0"+
    "\3\7\4\0\3\7\1\213\22\7\31\0\3\7\4\0"+
    "\17\7\1\214\6\7\31\0\3\7\4\0\10\7\1\215"+
    "\15\7\31\0\3\7\4\0\3\7\1\216\22\7\31\0"+
    "\3\7\4\0\20\7\1\217\5\7\31\0\3\7\4\0"+
    "\15\7\1\220\10\7\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5184];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\5\1\1\11\21\1\2\11"+
    "\5\1\10\11\1\0\1\11\5\0\1\1\1\0\24\1"+
    "\12\11\1\1\1\11\1\0\23\1\1\11\47\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    WordPainter painter;
    public ScannerF(java.io.Reader in,WordPainter painter) {
        yyline = 0;
        yychar = 0;
        this.zzReader = in;
        this.painter = painter;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScannerF(java.io.Reader in) {
      yyline = 1;
    yychar = 1;
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(TOK.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { painter.ERROR(yychar,yylength());
            } 
            // fall through
          case 58: break;
          case 2: 
            { 
            } 
            // fall through
          case 59: break;
          case 3: 
            { return new Symbol(TOK.TK_id,        yychar, yylength(), yytext());
            } 
            // fall through
          case 60: break;
          case 4: 
            { return new Symbol(TOK.TK_int,       yychar, yylength(), yytext());
            } 
            // fall through
          case 61: break;
          case 5: 
            { return new Symbol(TOK.TK_div,       yychar, yylength(), yytext());
            } 
            // fall through
          case 62: break;
          case 6: 
            { return new Symbol(TOK.TK_mult,      yychar, yylength(), yytext());
            } 
            // fall through
          case 63: break;
          case 7: 
            { return new Symbol(TOK.TK_plus,      yychar, yylength(), yytext());
            } 
            // fall through
          case 64: break;
          case 8: 
            { return new Symbol(TOK.TK_minus,     yychar, yylength(), yytext());
            } 
            // fall through
          case 65: break;
          case 9: 
            { return new Symbol(TOK.TK_equ,       yychar, yylength(), yytext());
            } 
            // fall through
          case 66: break;
          case 10: 
            { return new Symbol(TOK.TK_pow,       yychar, yylength(), yytext());
            } 
            // fall through
          case 67: break;
          case 11: 
            { return new Symbol(TOK.TK_mod,       yychar, yylength(), yytext());
            } 
            // fall through
          case 68: break;
          case 12: 
            { return new Symbol(TOK.TK_not,       yychar, yylength(), yytext());
            } 
            // fall through
          case 69: break;
          case 13: 
            { return new Symbol(TOK.TK_less,      yychar, yylength(), yytext());
            } 
            // fall through
          case 70: break;
          case 14: 
            { return new Symbol(TOK.TK_more,      yychar, yylength(), yytext());
            } 
            // fall through
          case 71: break;
          case 15: 
            { return new Symbol(TOK.TK_lpar,      yychar, yylength(), yytext());
            } 
            // fall through
          case 72: break;
          case 16: 
            { return new Symbol(TOK.TK_rpar,      yychar, yylength(), yytext());
            } 
            // fall through
          case 73: break;
          case 17: 
            { return new Symbol(TOK.TK_lbrc,      yychar, yylength(), yytext());
            } 
            // fall through
          case 74: break;
          case 18: 
            { return new Symbol(TOK.TK_rbrc,      yychar, yylength(), yytext());
            } 
            // fall through
          case 75: break;
          case 19: 
            { return new Symbol(TOK.TK_comma,     yychar, yylength(), yytext());
            } 
            // fall through
          case 76: break;
          case 20: 
            { return new Symbol(TOK.TK_colon,     yychar, yylength(), yytext());
            } 
            // fall through
          case 77: break;
          case 21: 
            { return new Symbol(TOK.TK_semicolon, yychar, yylength(), yytext());
            } 
            // fall through
          case 78: break;
          case 22: 
            { return new Symbol(TOK.TK_question,  yychar, yylength(), yytext());
            } 
            // fall through
          case 79: break;
          case 23: 
            { return new Symbol(TOK.TK_string,    yychar, yylength(), yytext());
            } 
            // fall through
          case 80: break;
          case 24: 
            { painter.COMMENT(yychar,yylength());
            } 
            // fall through
          case 81: break;
          case 25: 
            { return new Symbol(TOK.RW_if,        yychar, yylength(), yytext());
            } 
            // fall through
          case 82: break;
          case 26: 
            { return new Symbol(TOK.RW_do,        yychar, yylength(), yytext());
            } 
            // fall through
          case 83: break;
          case 27: 
            { return new Symbol(TOK.TK_inc,       yychar, yylength(), yytext());
            } 
            // fall through
          case 84: break;
          case 28: 
            { return new Symbol(TOK.TK_add,       yychar, yylength(), yytext());
            } 
            // fall through
          case 85: break;
          case 29: 
            { return new Symbol(TOK.TK_dec,       yychar, yylength(), yytext());
            } 
            // fall through
          case 86: break;
          case 30: 
            { return new Symbol(TOK.TK_sub,       yychar, yylength(), yytext());
            } 
            // fall through
          case 87: break;
          case 31: 
            { return new Symbol(TOK.TK_equequ,    yychar, yylength(), yytext());
            } 
            // fall through
          case 88: break;
          case 32: 
            { return new Symbol(TOK.TK_notequ,    yychar, yylength(), yytext());
            } 
            // fall through
          case 89: break;
          case 33: 
            { return new Symbol(TOK.TK_lessequ,   yychar, yylength(), yytext());
            } 
            // fall through
          case 90: break;
          case 34: 
            { return new Symbol(TOK.TK_moreequ,   yychar, yylength(), yytext());
            } 
            // fall through
          case 91: break;
          case 35: 
            { return new Symbol(TOK.TK_and,       yychar, yylength(), yytext());
            } 
            // fall through
          case 92: break;
          case 36: 
            { return new Symbol(TOK.TK_or,        yychar, yylength(), yytext());
            } 
            // fall through
          case 93: break;
          case 37: 
            { return new Symbol(TOK.TK_double,    yychar, yylength(), yytext());
            } 
            // fall through
          case 94: break;
          case 38: 
            { return new Symbol(TOK.TK_char,      yychar, yylength(), yytext());
            } 
            // fall through
          case 95: break;
          case 39: 
            { return new Symbol(TOK.RW_int,       yychar, yylength(), yytext());
            } 
            // fall through
          case 96: break;
          case 40: 
            { return new Symbol(TOK.RW_for,       yychar, yylength(), yytext());
            } 
            // fall through
          case 97: break;
          case 41: 
            { return new Symbol(TOK.RW_main,      yychar, yylength(), yytext());
            } 
            // fall through
          case 98: break;
          case 42: 
            { return new Symbol(TOK.RW_void,      yychar, yylength(), yytext());
            } 
            // fall through
          case 99: break;
          case 43: 
            { return new Symbol(TOK.RW_true,      yychar, yylength(), yytext());
            } 
            // fall through
          case 100: break;
          case 44: 
            { return new Symbol(TOK.RW_else,      yychar, yylength(), yytext());
            } 
            // fall through
          case 101: break;
          case 45: 
            { return new Symbol(TOK.RW_case,      yychar, yylength(), yytext());
            } 
            // fall through
          case 102: break;
          case 46: 
            { return new Symbol(TOK.RW_char,      yychar, yylength(), yytext());
            } 
            // fall through
          case 103: break;
          case 47: 
            { return new Symbol(TOK.RW_break,     yychar, yylength(), yytext());
            } 
            // fall through
          case 104: break;
          case 48: 
            { return new Symbol(TOK.RW_false,     yychar, yylength(), yytext());
            } 
            // fall through
          case 105: break;
          case 49: 
            { return new Symbol(TOK.RW_while,     yychar, yylength(), yytext());
            } 
            // fall through
          case 106: break;
          case 50: 
            { return new Symbol(TOK.RW_print,     yychar, yylength(), yytext());
            } 
            // fall through
          case 107: break;
          case 51: 
            { return new Symbol(TOK.RW_double,    yychar, yylength(), yytext());
            } 
            // fall through
          case 108: break;
          case 52: 
            { return new Symbol(TOK.RW_String,    yychar, yylength(), yytext());
            } 
            // fall through
          case 109: break;
          case 53: 
            { return new Symbol(TOK.RW_return,    yychar, yylength(), yytext());
            } 
            // fall through
          case 110: break;
          case 54: 
            { return new Symbol(TOK.RW_switch,    yychar, yylength(), yytext());
            } 
            // fall through
          case 111: break;
          case 55: 
            { return new Symbol(TOK.RW_default,   yychar, yylength(), yytext());
            } 
            // fall through
          case 112: break;
          case 56: 
            { return new Symbol(TOK.RW_boolean,   yychar, yylength(), yytext());
            } 
            // fall through
          case 113: break;
          case 57: 
            { return new Symbol(TOK.RW_continue,  yychar, yylength(), yytext());
            } 
            // fall through
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
