
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Language;

/** CUP generated class containing symbol constants. */
public class TOK {
  /* terminals */
  public static final int TK_equ = 43;
  public static final int RW_switch = 14;
  public static final int TK_comma = 53;
  public static final int TK_notequ = 40;
  public static final int TK_rbrc = 52;
  public static final int RW_break = 17;
  public static final int TK_lessequ = 41;
  public static final int TK_string = 23;
  public static final int RW_main = 2;
  public static final int RW_int = 7;
  public static final int TK_dec = 29;
  public static final int RW_for = 11;
  public static final int RW_true = 20;
  public static final int TK_sub = 31;
  public static final int TK_equequ = 39;
  public static final int RW_while = 12;
  public static final int TK_colon = 54;
  public static final int TK_or = 47;
  public static final int TK_pow = 36;
  public static final int RW_void = 3;
  public static final int TK_lpar = 49;
  public static final int TK_uminus = 38;
  public static final int RW_false = 21;
  public static final int RW_do = 13;
  public static final int RW_else = 10;
  public static final int TK_id = 27;
  public static final int TK_double = 26;
  public static final int EOF = 0;
  public static final int RW_boolean = 5;
  public static final int RW_print = 22;
  public static final int TK_more = 45;
  public static final int RW_continue = 18;
  public static final int error = 1;
  public static final int TK_int = 25;
  public static final int RW_double = 8;
  public static final int TK_question = 56;
  public static final int TK_mult = 34;
  public static final int TK_lbrc = 51;
  public static final int TK_not = 48;
  public static final int TK_and = 46;
  public static final int TK_char = 24;
  public static final int TK_semicolon = 55;
  public static final int TK_inc = 28;
  public static final int TK_div = 35;
  public static final int RW_String = 4;
  public static final int TK_less = 44;
  public static final int RW_default = 16;
  public static final int TK_moreequ = 42;
  public static final int RW_char = 6;
  public static final int TK_rpar = 50;
  public static final int RW_return = 19;
  public static final int TK_add = 30;
  public static final int TK_mod = 37;
  public static final int RW_if = 9;
  public static final int TK_minus = 33;
  public static final int RW_case = 15;
  public static final int TK_plus = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_main",
  "RW_void",
  "RW_String",
  "RW_boolean",
  "RW_char",
  "RW_int",
  "RW_double",
  "RW_if",
  "RW_else",
  "RW_for",
  "RW_while",
  "RW_do",
  "RW_switch",
  "RW_case",
  "RW_default",
  "RW_break",
  "RW_continue",
  "RW_return",
  "RW_true",
  "RW_false",
  "RW_print",
  "TK_string",
  "TK_char",
  "TK_int",
  "TK_double",
  "TK_id",
  "TK_inc",
  "TK_dec",
  "TK_add",
  "TK_sub",
  "TK_plus",
  "TK_minus",
  "TK_mult",
  "TK_div",
  "TK_pow",
  "TK_mod",
  "TK_uminus",
  "TK_equequ",
  "TK_notequ",
  "TK_lessequ",
  "TK_moreequ",
  "TK_equ",
  "TK_less",
  "TK_more",
  "TK_and",
  "TK_or",
  "TK_not",
  "TK_lpar",
  "TK_rpar",
  "TK_lbrc",
  "TK_rbrc",
  "TK_comma",
  "TK_colon",
  "TK_semicolon",
  "TK_question"
  };
}

